name: Publish

on:
    release:
        types: [published, edited]

jobs:
    publish:
        name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: True
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: [3.6, 3.7, 3.8, '3.9.0-alpha - 3.9']

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}

            - name: Python info
              run: |
                which python
                python --version

            - name: Install wheel
              if: matrix.python-version == '3.9.0-alpha - 3.9'
              run: pip install wheel

            - name: Install dependencies
              run: pip install .[build]

            - name: Build wheels
              run: python setup.py sdist bdist_wheel

            - name: Upload wheels
              uses: actions/upload-artifact@v1
              with:
                name: dist_${{ matrix.os }}_x64_${{ matrix.python-version }}
                path: dist

            - name: Publish the package
              uses: pypa/gh-action-pypi-publish@master
              with:
                user: __token__
                password: ${{ secrets.PYPI_TOKEN }}
